sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-hongkong.aliyuncs.com
    access-key-id: LTAI5tJnFhiidjvjDgGrCyeT
    access-key-secret: 4ynQvBma8fW9MbEQ4RukYOM6pud8fP
    bucket-name: sky-take-out-moyu